In [1]:
import pickle
with open('train_sentence_transformer.pkl', 'rb') as f:
    train = pickle.load(f)
with open('val_sentence_transformer.pkl', 'rb') as f:
    val = pickle.load(f)
with open('test_sentence_transformer.pkl', 'rb') as f:
    test = pickle.load(f)

In [2]:
import json
with open('test.json', encoding = 'utf8') as json_file:
    data = json.load(json_file)
    
conversations = []
summaries = []
for i in range(0, len(data)):
    if len(data[i]['dialogue'].split('\r\n')) > 1:
        sentences = data[i]['dialogue'].split('\r\n')
    else:
        sentences = data[i]['dialogue'].split('\n')

    conversations.append(sentences)
    summaries.append(data[i]['summary'].strip('\n').replace('\r\nt', ' '))

In [3]:
import numpy as np
length = []
for i in range(0, len(train)):
    length.append(len(train[i]))
for i in range(0, len(val)):
    length.append(len(val[i]))
for i in range(0, len(test)):
    length.append(len(test[i]))
X = []
for i in range(0, len(train)):
    for j in range(0, len(train[i])):
        X.append(np.array(train[i][j]))
for i in range(0, len(val)):
    for j in range(0,len(val[i])):
        X.append(np.array(val[i][j]))
for i in range(0, len(test)):
    for j in range(0, len(test[i])):
        X.append(np.array(test[i][j]))

In [4]:
from hmmlearn import hmm

In [5]:
remodel = hmm.GaussianHMM(n_components=4, n_iter = 50, covariance_type = 'diag', verbose = True, init_params="cm", params="cmts")
remodel.startprob_ = np.array([1, 0.0, 0.0, 0.0])
remodel.transmat_ = np.array([
                 [0.33, 0.34, 0.33, 0],
                 [0.0, 0.33, 0.34, 0.33],
                 [0.0, 0.0, 0.5, 0.5],
                 [0.0, 0.0, 0.0, 1.0]]
                            )

In [6]:
remodel.startprob_

array([1., 0., 0., 0.])

In [7]:
remodel.transmat_

array([[0.33, 0.34, 0.33, 0.  ],
       [0.  , 0.33, 0.34, 0.33],
       [0.  , 0.  , 0.5 , 0.5 ],
       [0.  , 0.  , 0.  , 1.  ]])

In [8]:
remodel.fit(X, length)

         1 -272805.13153256             +nan
         2 -264097.95087766   +8707.18065490
         3 -263840.90952861    +257.04134906
         4 -263782.24137520     +58.66815340
         5 -263781.90776199      +0.33361322
         6 -263778.10659836      +3.80116362
         7 -263768.90956129      +9.19703707
         8 -263768.90846337      +0.00109792


GaussianHMM(init_params='cm', n_components=4, n_iter=50, params='cmts',
            verbose=True)

In [9]:
remodel.transmat_

array([[0.82242995, 0.08878503, 0.08878502, 0.        ],
       [0.        , 0.84848478, 0.10101014, 0.05050507],
       [0.        , 0.        , 0.87323942, 0.12676058],
       [0.        , 0.        , 0.        , 1.        ]])

In [10]:
remodel.startprob_

array([1., 0., 0., 0.])

In [11]:
def encode_convs(profix):
    sent_label = []
    with open(profix + '_sentence_transformer.pkl', 'rb') as f:
        data = pickle.load(f)
    for i in range(0, len(data)):
        labels = remodel.decode(np.array(data[i]))[1]
        sent_label.append(labels)
    
    with open(profix + '_sent_trans_cons_label.pkl', 'wb') as f:
        pickle.dump(sent_label, f)
    return sent_label

In [12]:
l = encode_convs('train')

In [13]:
l = encode_convs('val')

In [14]:
l = encode_convs('test')